name: Publish Python Package to PyPI

on:
  push:
    branches:
      - pypi-test

jobs:
  test-publish:
    runs-on: ubuntu-latest
    environment: pypi-test
    permissions:
      id-token: write # to authenticate as Trusted Publisher to pypi.org
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip"

      - run: pip install build
      - run: python -m build

      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          